//#############################################################################
//
// FILE:   mppt_dcdc.h
//
//TITLE: solution hardware abstraction layer header file
//        This file consists of common variables and functions
//        for a particular hardware board, like functions to read current
//        and voltage signals on the board and functions to setup the
//        basic peripherals of the board
//
//#############################################################################
// $TI Release: TIDM_SOLAR_DCDC v1.00.00.00 $
// $Release Date: Tue Aug 26 14:08:12 CDT 2025 $
// $Copyright:
// Copyright (C) 2021 Texas Instruments Incorporated - http://www.ti.com/
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
//
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
//
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the
//   distribution.
//
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
// $
//#############################################################################


#ifndef MPPT_DCDC_H
#define MPPT_DCDC_H

#ifdef __cplusplus

extern "C" {
#endif

//************************ the includes *************************************

#include <stdint.h>

#ifndef __TMS320C28XX_CLA__
#include <math.h>
#else
#include <CLAmath.h>
#endif

//
// this is the file generated by the powerSUITE page for this system
//
#include <mppt_setting.h>
#include <mppt_Init.h>

//
// Library header files
//
//#include "dlog_4ch.h"
//#include "emavg.h"

#include "mppt_pno.h"

#include "mppt_incc.h"

#ifndef __TMS320C28XX_CLA__
//#include "sfra_f32.h"
//#include "sfra_gui_scicomms_driverlib.h"
#endif

#ifndef __TMS320C28XX_CLA__
#include "DCLF32.h"
#define MPPTDCDC_GI DCL_PI
#define MPPTDCDC_GV DCL_PI
#define MPPTDCDC_GI_RUN DCL_runPI_C2
#define MPPTDCDC_GV_RUN DCL_runPI_C3
#endif
//Voltage_Loop

//
// Function prototypes
//
void MPPTDCDC_globalVariablesInit(void);
void MPPTDCDC_updateFaultStatus(void);
void MPPTDCDC_setupSFRA(void);
void MPPTDCDC_runSFRABackGroundTasks(void);

typedef enum
{
    STATE_NO_FAULT = 0,
    STATE_FAULT = 1,

}MPPTDCDC_stateType;

extern MPPTDCDC_stateType MPPTDCDC_state;

typedef struct
{
    bool fault_iL_overCurrent;
    bool fault_vPanel_overVoltage;
    bool fault_vBus_overVoltage;
}MPPTDCDC_struct_boardFaultFlags;

extern MPPTDCDC_struct_boardFaultFlags MPPTDCDC_boardFaultFlags;

extern MPPT_PNO_F mppt_pno1;


//
// Exponential Average
//
//extern EMAVG MPPTDCDC_EMAVG;

#define EMAVG_MACRO(in, out, multiplier) out = ((in - out)*multiplier) + out;
//Multiplier = (2*pi*f_cutoff)/f_sampling
//
//
//
// Controller variables

extern MPPTDCDC_GI MPPTDCDC_gi_id;

extern MPPTDCDC_GV MPPTDCDC_gv_vBus;

//extern MPPTDCDC_GI Test;

extern float32_t MPPTDCDC_gv_vBus_out;

extern float32_t MPPTDCDC_gi_id_out;
//
//
// SOLAR variables
//
extern MPPT_INCC_F MPPTDCDC_incc1;
//
extern volatile float32_t MPPTDCDC_idRef_pu;
extern volatile float32_t MPPTDCDC_idRef;

extern float32_t MPPTDCDC_vOut_sensed_pu;

extern float32_t MPPTDCDC_vOut_sensedOffset_pu;

extern float32_t MPPTDCDC_iL_sensed_pu;

extern volatile float32_t MPPTDCDC_iL_sensed_Avg_pu;

extern float32_t MPPTDCDC_iL_sensedOffset_pu;

extern float32_t MPPTDCDC_vPanel_sensed_pu,
                 MPPTDCDC_vBus_sensed_pu,
                 MPPTDCDC_vBus_sensed,
                 MPPTDCDC_vBus_sensed_filter;


extern volatile float32_t MPPTDCDC_vPanel_sensed_Avg_pu;


extern float32_t MPPTDCDC_vPanel_sensedOffset_pu;


extern float32_t MPPTDCDC_vBus_sensedOffset_pu;

//
// Absolute/Display Values
//

extern volatile float32_t MPPTDCDC_guiVpanel,
                          MPPTDCDC_guiVbus;


extern volatile float32_t MPPTDCDC_guivOut_inst;


extern volatile float32_t MPPTDCDC_guiiL_inst,MPPTDCDC_guiiL_Avg;

//
// PWM duty variables
//
extern float32_t MPPTDCDC_duty_A,
                 MPPTDCDC_duty_B, MPPTDCDC_llc_prd;
//
// User command to clear the PWM trip and restore PWM signals
//
extern volatile uint16_t MPPTDCDC_clearPWMTrip;

//
// User command to update the duty of PWM outputs
// Make sure that the desired duty values are written prior
// using this command
//
extern volatile uint16_t MPPTDCDC_updateDuty;


//
// User command to reset board state and fault flags
//
extern uint16_t MPPTDCDC_resetAllFaultStatus;

//
// MPPT related variables
//
extern float32_t MPPTDCDC_Vpvref_Out;

extern uint16_t MPPTDCDC_MPPT_ENABLE;
extern uint16_t MPPTDCDC_Run_MPPT;
extern uint16_t MPPTDCDC_MPPT_slew;

extern MPPT_PNO_F mppt_pno1;


//
// DLOG
//
//extern DLOG_4CH MPPTDCDC_dLog1;
//extern float32_t MPPTDCDC_dBuff1[MPPTDCDC_DLOG_SIZE];
//extern float32_t MPPTDCDC_dBuff2[MPPTDCDC_DLOG_SIZE];
//extern float32_t MPPTDCDC_dBuff3[MPPTDCDC_DLOG_SIZE];
//extern float32_t MPPTDCDC_dBuff4[MPPTDCDC_DLOG_SIZE];
//extern float32_t MPPTDCDC_dVal1;
//extern float32_t MPPTDCDC_dVal2;
//extern float32_t MPPTDCDC_dVal3;
//extern float32_t MPPTDCDC_dVal4;

//
// SFRA Related Variables
//
extern float32_t MPPTDCDC_plantMagVect[MPPT_DCDC_SFRA_FREQ_LENGTH];
extern float32_t MPPTDCDC_plantPhaseVect[MPPT_DCDC_SFRA_FREQ_LENGTH];
extern float32_t MPPTDCDC_olMagVect[MPPT_DCDC_SFRA_FREQ_LENGTH];
extern float32_t MPPTDCDC_olPhaseVect[MPPT_DCDC_SFRA_FREQ_LENGTH];
extern float32_t MPPTDCDC_freqVect[MPPT_DCDC_SFRA_FREQ_LENGTH];

//extern SFRA_F32 MPPTDCDC_sfra1;

extern float32_t MPPTDCDC_activePower;


//
// Read all currents and voltage parameters
//
#pragma FUNC_ALWAYS_INLINE(MPPTDCDC_readCurrentAndVoltageSignals)
static inline void MPPTDCDC_readCurrentAndVoltageSignals()
{

    MPPTDCDC_vOut_sensed_pu = ((float32_t)MPPT_DCDC_HAL_VOUT_FB *
                               MPPT_DCDC_ADC_PU_SCALE_FACTOR);


    MPPTDCDC_iL_sensed_pu = ((float32_t)MPPT_DCDC_HAL_IL_FB *
                                MPPT_DCDC_ADC_PU_SCALE_FACTOR);


    MPPTDCDC_vPanel_sensed_pu = ((float32_t)MPPT_DCDC_VPANEL_FB *
                              MPPT_DCDC_ADC_PU_SCALE_FACTOR);

    MPPTDCDC_vBus_sensed_pu = ((float32_t)MPPT_DCDC_VBUS_FB *
                              MPPT_DCDC_ADC_PU_SCALE_FACTOR);

}

//
// Converts per unit measurements to absolute values
//
static inline void MPPTDCDC_puToVal_conversion()
{
    MPPTDCDC_guivOut_inst =  MPPTDCDC_vOut_sensed_pu * MPPT_DCDC_VOUT_MAX_SENSE;

    MPPTDCDC_guiiL_inst =  MPPTDCDC_iL_sensed_pu * MPPT_DCDC_IL_MAX_SENSE;

    MPPTDCDC_guiiL_Avg = MPPTDCDC_iL_sensed_Avg_pu* MPPT_DCDC_IL_MAX_SENSE;

    MPPTDCDC_guiVpanel =  MPPTDCDC_vPanel_sensed_pu * MPPT_DCDC_VPANEL_MAX_SENSE;

    MPPTDCDC_guiVbus =  MPPTDCDC_vBus_sensed_pu * MPPT_DCDC_VDCBUS_MAX_SENSE;
}

//
// Updates the PWM duty values for 2 phases
//
#pragma FUNC_ALWAYS_INLINE(MPPTDCDC_updateBoostPWM)

static inline void MPPTDCDC_updateBoostPWM(float32_t dutyA,
                                     float32_t dutyB)
{

    dutyA = (dutyA > MPPT_DCDC_DUTY_MAX) ? MPPT_DCDC_DUTY_MAX : dutyA;

    dutyA = (dutyA < MPPT_DCDC_DUTY_MIN) ? MPPT_DCDC_DUTY_MIN : dutyA;

    dutyB = (dutyB > MPPT_DCDC_DUTY_MAX) ? MPPT_DCDC_DUTY_MAX : dutyB;
    dutyB = (dutyB < MPPT_DCDC_DUTY_MIN) ? MPPT_DCDC_DUTY_MIN : dutyB;

    MPPTDCDC_HAL_updateCMPA(MPPT_DCDC_HIGH_FREQ_PWM_A_BASE, dutyA);

    MPPTDCDC_HAL_updateCMPA(MPPT_DCDC_HIGH_FREQ_PWM_B_BASE, dutyB);
}
//
//**************code for LLC PWM************************
#pragma FUNC_ALWAYS_INLINE(MPPTDCDC_updateLLCPWM)
static inline void MPPTDCDC_updateLLCPWM(float32_t llc_prd)
{

    llc_prd = (llc_prd > 0.5f*MPPT_DCDC_LLC_PWM_PRD_MAX) ? 0.5f*MPPT_DCDC_LLC_PWM_PRD_MAX : llc_prd;
    llc_prd = (llc_prd < 0.5f*MPPT_DCDC_LLC_PWM_PRD_MIN) ? 0.5f*MPPT_DCDC_LLC_PWM_PRD_MIN : llc_prd;

    MPPTDCDC_HAL_updateTBPRD(MPPT_DCDC_LLC_PWM_BASE, llc_prd);
}
//***********end LLC****************************
//
// Manually clear OST flags for PWMs
//
#pragma FUNC_ALWAYS_INLINE(MPPTDCDC_clearAllPWMTrips)
static inline void MPPTDCDC_clearAllPWMTrips()
{
    MPPTDCDC_HAL_clearPWMTripFlags(MPPT_DCDC_HIGH_FREQ_PWM_A_BASE);
    MPPTDCDC_HAL_clearPWMTripFlags(MPPT_DCDC_HIGH_FREQ_PWM_B_BASE);
    MPPTDCDC_HAL_clearPWMTripFlags(MPPT_DCDC_LLC_PWM_BASE);
}

//*******code for SOLAR INCC MPPT*******************
// Run the MPPT algo
//
#pragma FUNC_ALWAYS_INLINE(MPPTDCDC_runMPPT)
static inline void MPPTDCDC_runMPPT()
{

    MPPT_INCC_F_MACRO(MPPTDCDC_incc1);

}
//***************************end of INCC related code*******************

//
// Current Control Loop Execute Function
//
#pragma FUNC_ALWAYS_INLINE(MPPTDCDC_runCurrentLoop)
static inline void MPPTDCDC_runCurrentLoop(void)
{

//
// Closed loop operation with SFRA enabled
//
#if MPPT_DCDC_SFRA_TYPE == MPPT_DCDC_SFRA_CURRENT

        MPPTDCDC_gi_id_out = MPPTDCDC_GI_RUN(&MPPTDCDC_gi_id,
                                           SFRA_F32_inject(MPPTDCDC_idRef_pu),
                                           MPPTDCDC_iL_sensed_pu);
        SFRA_F32_collect(&MPPTDCDC_gi_id_out, &MPPTDCDC_iL_sensed_pu);

#else
        // Closed loop operation with SFRA disabled
        //
        MPPTDCDC_gi_id_out = MPPTDCDC_GI_RUN(&MPPTDCDC_gi_id,MPPTDCDC_idRef_pu,MPPTDCDC_iL_sensed_pu);
#endif

        MPPTDCDC_gi_id_out = (MPPTDCDC_gi_id_out > 1.0f) ? 1.0f : MPPTDCDC_gi_id_out;
        MPPTDCDC_gi_id_out = (MPPTDCDC_gi_id_out < 0.0f) ? 0.0f : MPPTDCDC_gi_id_out;

}

//
// Lab1 ISR code
//
#pragma FUNC_ALWAYS_INLINE(MPPTDCDC_runISR1_lab1)
static inline void MPPTDCDC_runISR1_lab1(void)
{
    //
    // Read ADC sampled voltage and current values
    //
    MPPTDCDC_readCurrentAndVoltageSignals();
    //
    EMAVG_MACRO(MPPTDCDC_iL_sensed_pu, MPPTDCDC_iL_sensed_Avg_pu, (float)0.000528);
    EMAVG_MACRO(MPPTDCDC_vPanel_sensed_pu, MPPTDCDC_vPanel_sensed_Avg_pu, (float)0.000528);//f_cutoff = 4.2Hz
    //Multiplier = (2*pi*f_cutoff)/f_sampling
    //
    //
    // Clear the PWM trips when MPPTDCDC_clearPWMTrip
    // is written to '1' from the watch window
    //
    if(MPPTDCDC_clearPWMTrip == 1U)
    {
      MPPTDCDC_clearPWMTrip = 0;
      MPPTDCDC_clearAllPWMTrips();
      MPPTDCDC_updateDuty = 1U;
    }


    if (MPPTDCDC_updateDuty == 1U)
    {
        MPPTDCDC_updateDuty = 0;
        MPPTDCDC_updateBoostPWM(MPPTDCDC_duty_A, MPPTDCDC_duty_B);
        MPPTDCDC_updateLLCPWM(MPPTDCDC_llc_prd);
    }

    MPPTDCDC_HAL_clearPWMInterruptFlag(MPPT_DCDC_ISR1_TRIG_BASE);
}

//
// Lab2 ISR code. MPPT current loop only
//
#pragma FUNC_ALWAYS_INLINE(MPPTDCDC_runISR1_lab2)
static inline void MPPTDCDC_runISR1_lab2(void)
{
    //
    // Read ADC sampled voltage and current values
    //
    MPPTDCDC_readCurrentAndVoltageSignals();
    //
    EMAVG_MACRO(MPPTDCDC_iL_sensed_pu, MPPTDCDC_iL_sensed_Avg_pu, (float)0.001);
    EMAVG_MACRO(MPPTDCDC_vPanel_sensed_pu, MPPTDCDC_vPanel_sensed_Avg_pu, (float)0.001);//f_cutoff = 8.4Hz
    //Multiplier = (2*pi*f_cutoff)/f_sampling
    //
    //
    // Clear the PWM trips when MPPTDCDC_clearPWMTrip
    // is written to '1' from the watch window
    //
    if(MPPTDCDC_clearPWMTrip == 1U)
    {
            MPPTDCDC_clearPWMTrip = 0;
            MPPTDCDC_clearAllPWMTrips();
            MPPTDCDC_updateDuty = 1U;
    }

    if (MPPTDCDC_updateDuty)
    {
        //
        // Run the current close loop
        //
        MPPTDCDC_runCurrentLoop();

        MPPTDCDC_duty_A = MPPTDCDC_gi_id_out;
        MPPTDCDC_duty_B = MPPTDCDC_gi_id_out;

        MPPTDCDC_updateBoostPWM(MPPTDCDC_duty_A, MPPTDCDC_duty_B);

    }

    MPPTDCDC_vBus_sensed=MPPTDCDC_vBus_sensed_pu*MPPT_DCDC_VDCBUS_MAX_SENSE;
    MPPTDCDC_vBus_sensed_filter=Low_Pass_Filter*(MPPTDCDC_vBus_sensed_filter-MPPTDCDC_vBus_sensed)+MPPTDCDC_vBus_sensed;

//    MPPTDCDC_dVal1 = MPPTDCDC_iL_sensed_pu*MPPT_DCDC_IL_MAX_SENSE;
//    MPPTDCDC_dVal2 = MPPTDCDC_vPanel_sensed_pu * MPPT_DCDC_VPANEL_MAX_SENSE;
//    MPPTDCDC_dVal3 = MPPTDCDC_vBus_sensed_pu * MPPT_DCDC_VDCBUS_MAX_SENSE;
//    MPPTDCDC_dVal4 = MPPTDCDC_vOut_sensed_pu * MPPT_DCDC_VOUT_MAX_SENSE;
//    MPPTDCDC_dLog1.status = 2;//Added this to force status=2 all the time. This is needed for triggering DC signals.
//    //In this design all the signals in the DC/DC boost stage are DC signals.
//    DLOG_4CH_run(&MPPTDCDC_dLog1);


    MPPTDCDC_HAL_clearPWMInterruptFlag(MPPT_DCDC_ISR1_TRIG_BASE);
}

//
//Lab3 ISR code. MPPT voltage loop and current loop closed

#pragma FUNC_ALWAYS_INLINE(MPPTDCDC_runISR1_lab3)
static inline void MPPTDCDC_runISR1_lab3(void)
{
    //
    // Read ADC sampled voltage and current values
    //
    MPPTDCDC_readCurrentAndVoltageSignals();
    //
    EMAVG_MACRO(MPPTDCDC_iL_sensed_pu, MPPTDCDC_iL_sensed_Avg_pu, (float)0.001);//f_cutoff = 8.4Hz
    EMAVG_MACRO(MPPTDCDC_vPanel_sensed_pu, MPPTDCDC_vPanel_sensed_Avg_pu, (float)0.001);//f_cutoff = 8.4Hz
    //Multiplier = (2*pi*f_cutoff)/f_sampling
    //

    //
    // Clear the PWM trips when MPPTDCDC_clearPWMTrip
    // is written to '1' from the watch window
    //
    if(MPPTDCDC_clearPWMTrip == 1U)
    {
            MPPTDCDC_clearPWMTrip = 0;
            MPPTDCDC_clearAllPWMTrips();
            MPPTDCDC_updateDuty = 1U;
    }

    if (MPPTDCDC_updateDuty)
    {


        //Voltage control loop

        //This volt loop has +ve feedback (compared to the conventional -ve feedback) since for higher Vpanel, i.e., panel volt
        //we want higher control output, i.e., in this case higher boost current and vice versa. Thus the volt loop controller (MPPTDCDC_GV_RUN)
        //connections below are reversed for feedback and reference signals
        //PV panel reference(MPPTDCDC_Vpvref_Out) is connected to the controller feedback.
        //MPPTDCDC_vPanel_sensed_pu is the PV panel feedback and is connected to the controller reference.

        //MPPTDCDC_Vpvref_Out is the output of the MPPT algorithm. This volt loop controller regulates it's out to maintain the input
        //of the boost converter at MPPTDCDC_Vpvref_Out

        //MPPTDCDC_idRef_pu is the output of the controller and is used as Reference for inner current loop

#if     MPPT_DCDC_SFRA_TYPE == MPPT_DCDC_SFRA_VOLTAGE

        MPPTDCDC_idRef_pu = MPPTDCDC_GV_RUN(&MPPTDCDC_gv_vBus,SFRA_F32_inject(MPPTDCDC_vPanel_sensed_pu),MPPTDCDC_Vpvref_Out);
        MPPTDCDC_gv_vBus_out = MPPTDCDC_idRef_pu;
        SFRA_F32_collect((float32_t *)&MPPTDCDC_gv_vBus_out, (float32_t *)&MPPTDCDC_Vpvref_Out);

#else

        MPPTDCDC_idRef_pu = MPPTDCDC_GV_RUN(&MPPTDCDC_gv_vBus,MPPTDCDC_vPanel_sensed_pu,MPPTDCDC_Vpvref_Out);

#endif

        //Current control loop
        MPPTDCDC_runCurrentLoop();

        MPPTDCDC_duty_A = MPPTDCDC_gi_id_out;

        MPPTDCDC_duty_B = MPPTDCDC_gi_id_out;

        MPPTDCDC_updateBoostPWM(MPPTDCDC_duty_A, MPPTDCDC_duty_B);


//Enable MPPT when DC Bus is higher than PV panel input

        if(MPPTDCDC_vBus_sensed_pu > 0.30f)
        {
            MPPTDCDC_MPPT_ENABLE=1;
            MPPTDCDC_incc1.mppt_enable = 1;
        }
        else
        {
            MPPTDCDC_MPPT_ENABLE=0;
            MPPTDCDC_incc1.mppt_enable = 0;
        }

    }

    MPPTDCDC_vBus_sensed=MPPTDCDC_vBus_sensed_pu*MPPT_DCDC_VDCBUS_MAX_SENSE;
    MPPTDCDC_vBus_sensed_filter=Low_Pass_Filter*(MPPTDCDC_vBus_sensed_filter-MPPTDCDC_vBus_sensed)+MPPTDCDC_vBus_sensed;

    MPPTDCDC_HAL_clearPWMInterruptFlag(MPPT_DCDC_ISR1_TRIG_BASE);
}




// ISR2 code
//
#pragma FUNC_ALWAYS_INLINE(MPPTDCDC_runISR2)
static inline void MPPTDCDC_runISR2(void)
{
    //
    // Converting per unit values to absolute measurements
    //
    MPPTDCDC_puToVal_conversion();


/*    if(MPPTDCDC_vPanel_sensed_Avg_pu > 0.15f)
    {
        MPPTDCDC_MPPT_ENABLE=1;
        MPPTDCDC_incc1.mppt_enable = 1;
    }
    else
    {
        MPPTDCDC_MPPT_ENABLE=0;
        MPPTDCDC_incc1.mppt_enable = 0;
    }*/


    if(MPPTDCDC_MPPT_ENABLE==1)
    {
        if(MPPTDCDC_MPPT_slew==0)
        {
            MPPTDCDC_Run_MPPT=1;
            MPPTDCDC_MPPT_slew=100;
        }
        else
        MPPTDCDC_MPPT_slew--;
    }

    if (MPPTDCDC_Run_MPPT == 1)
    {
        MPPTDCDC_Run_MPPT = 0;
        // MPPT routine
        MPPTDCDC_incc1.Ipv = MPPTDCDC_iL_sensed_Avg_pu;// Average PV current;
        MPPTDCDC_incc1.Vpv = MPPTDCDC_vPanel_sensed_Avg_pu;//Average PV panel voltage;

        MPPTDCDC_runMPPT();

        MPPTDCDC_Vpvref_Out = MPPTDCDC_incc1.VmppOut;

    }


}



#endif



